// ABOUTME: Cargo build script registering the Tauri app command manifest and ACL hooks.
// ABOUTME: App-local commands require explicit capabilities; no wildcard default grant.
use tauri_build::{AppManifest, Attributes, try_build};

/// Complete reviewed list of app-local IPC command names registered in `invoke_handler`.
///
/// Every `#[tauri::command]` registered in `src/lib.rs` via `generate_handler!` MUST appear
/// here. The build-time app manifest turns these into `allow-<command>` ACL permissions
/// (see `permissions/autogenerated/`) so capabilities grant them explicitly instead of
/// allowing all app commands by default. Adding a command to `generate_handler!` without
/// adding it here and to `permissions/app-commands.toml` fails the security-conformance
/// test in `storage/tests.rs` and leaves the command denied at runtime.
///
/// Command names are the snake_case function names; the autogenerated permission identifiers
/// replace underscores with hyphens (`show_snap_overlay` -> `allow-show-snap-overlay`).
const APP_COMMANDS: &[&str] = &[
  // Window / overlay lifecycle
  "show_snap_overlay",
  "set_pin",
  "resize_window_height",
  "notify_ready",
  "region_screenshot_get_backdrop",
  "region_screenshot_get_backdrop_data",
  "region_screenshot_reveal",
  "region_screenshot_confirm",
  "region_screenshot_cancel",
  "start_region_screenshot",
  // LLM providers and models
  "list_provider_instances",
  "save_provider_instance",
  "set_provider_enabled",
  "delete_provider_instance",
  "reorder_provider_instances",
  "list_provider_models",
  "list_all_provider_models",
  "save_manual_model",
  "set_model_enabled",
  "set_model_adapter_id",
  "update_model_config",
  "delete_provider_model",
  "delete_provider_models",
  "apply_provider_model_sync",
  "apply_provider_model_sync_failure",
  // Provider HTTP (brokered frontend provider transport)
  "provider_http_request",
  "provider_http_stream",
  "cancel_provider_http",
  // Translation profiles and service translation
  "list_translation_profiles",
  "get_translation_profile",
  "save_translation_profile",
  "set_translation_profile_enabled",
  "delete_translation_profile",
  "translate_service_profile",
  "detect_service_profile_language",
  // OCR services
  "list_ocr_services",
  "get_ocr_service",
  "save_ocr_service",
  "delete_ocr_service",
  "recognize_ocr",
  // Speech services
  "list_speech_services",
  "get_speech_service",
  "save_speech_service",
  "delete_speech_service",
  "synthesize_speech",
  "cancel_speech_synthesis",
  // Plugin packages (signed install lifecycle; no execution)
  "preview_plugin_package",
  "approve_plugin_package",
  "discard_plugin_package_preview",
  "list_installed_plugin_versions",
  "set_default_plugin_package",
  "list_plugin_publishers",
  "approve_user_plugin_publisher",
  "revoke_plugin_publisher",
  "restore_plugin_publisher",
  "remove_plugin_publisher",
  "uninstall_plugin_version",
  "get_plugin_version_dependencies",
  // Runtime lifecycle (pin/upgrade/rollback)
  "preview_integration_runtime_upgrade",
  "apply_integration_runtime_upgrade",
  "preview_integration_runtime_rollback",
  "apply_integration_runtime_rollback",
  "discard_integration_runtime_snapshot",
  // Service integrations (plugin instances)
  "list_service_integration_definitions",
  "list_integration_instances",
  "get_integration_instance",
  "save_integration_instance",
  "set_integration_instance_enabled",
  "list_integration_instance_dependencies",
  "delete_integration_instance",
  "validate_integration_instance",
  // Translation history
  "record_translation_history_completion",
  "list_translation_history",
  "get_translation_history",
  "get_translation_history_many",
  "list_translation_history_model_facets",
  "delete_translation_history",
  "delete_all_translation_history",
  // Settings
  "get_app_settings",
  "update_app_settings",
  "set_app_theme",
  "set_app_ui_language",
  "set_app_shortcuts",
  "set_app_default_ocr_service",
  "set_app_default_speech_service",
  // Import / export
  "export_configuration",
  "preview_configuration_import",
  "import_configuration",
];

fn main() {
  // Register the app command manifest so invoke_handler commands are ACL-gated. Without a
  // manifest Tauri allows every app command by default; with one, each command needs an
  // explicit `allow-<command>` permission granted through a capability.
  let attributes = Attributes::new().app_manifest(AppManifest::new().commands(APP_COMMANDS));
  try_build(attributes).expect("tauri-build failed");
}
