[package]
name = "langnext-google-cloud-protocol"
version = "1.2.0"
edition = "2021"
publish = false
license = "Apache-2.0"

[lib]
crate-type = ["rlib"]

[dependencies]
serde = { version = "1", default-features = false, features = ["alloc", "derive"] }
serde_json = { version = "1", default-features = false, features = ["alloc"] }

[profile.release]
opt-level = "z"
lto = true
codegen-units = 1
panic = "abort"
strip = true
