// Generated by `wit-bindgen` 0.41.0. DO NOT EDIT!
// Options used:
//   * runtime_path: "wit_bindgen_rt"
#[rustfmt::skip]
#[allow(dead_code, clippy::all)]
pub mod langnext {
    pub mod runtime_plugin {
        #[allow(dead_code, async_fn_in_trait, unused_imports, clippy::all)]
        pub mod common {
            #[used]
            #[doc(hidden)]
            static __FORCE_SECTION_REF: fn() = super::super::super::__link_custom_section_describing_imports;
            use super::super::super::_rt;
            /// Bounded UTF-8 request identifier (never credential material).
            pub type RequestId = _rt::String;
            /// Bounded application language identifier (e.g. `zh`, `en`).
            pub type LanguageId = _rt::String;
            /// Bounded, validated UTF-8 JSON bytes. Carries copied config/preferences only;
            /// never credential material.
            pub type JsonBytes = _rt::Vec<u8>;
            /// Stable plugin failure codes. Messages are bounded and never contain secrets.
            #[derive(Clone)]
            pub enum PluginError {
                InvalidRequest(_rt::String),
                InvalidConfiguration,
                InvalidInput(_rt::String),
                Auth,
                PermissionDenied,
                QuotaExceeded,
                RateLimited,
                UnsupportedInput(_rt::String),
                UnsupportedLanguage(_rt::String),
                Network(_rt::String),
                Timeout,
                InvalidResponse(_rt::String),
                ProviderUnavailable,
                PluginUnavailable,
                Cancelled,
                Internal(_rt::String),
            }
            impl ::core::fmt::Debug for PluginError {
                fn fmt(
                    &self,
                    f: &mut ::core::fmt::Formatter<'_>,
                ) -> ::core::fmt::Result {
                    match self {
                        PluginError::InvalidRequest(e) => {
                            f.debug_tuple("PluginError::InvalidRequest")
                                .field(e)
                                .finish()
                        }
                        PluginError::InvalidConfiguration => {
                            f.debug_tuple("PluginError::InvalidConfiguration").finish()
                        }
                        PluginError::InvalidInput(e) => {
                            f.debug_tuple("PluginError::InvalidInput").field(e).finish()
                        }
                        PluginError::Auth => f.debug_tuple("PluginError::Auth").finish(),
                        PluginError::PermissionDenied => {
                            f.debug_tuple("PluginError::PermissionDenied").finish()
                        }
                        PluginError::QuotaExceeded => {
                            f.debug_tuple("PluginError::QuotaExceeded").finish()
                        }
                        PluginError::RateLimited => {
                            f.debug_tuple("PluginError::RateLimited").finish()
                        }
                        PluginError::UnsupportedInput(e) => {
                            f.debug_tuple("PluginError::UnsupportedInput")
                                .field(e)
                                .finish()
                        }
                        PluginError::UnsupportedLanguage(e) => {
                            f.debug_tuple("PluginError::UnsupportedLanguage")
                                .field(e)
                                .finish()
                        }
                        PluginError::Network(e) => {
                            f.debug_tuple("PluginError::Network").field(e).finish()
                        }
                        PluginError::Timeout => {
                            f.debug_tuple("PluginError::Timeout").finish()
                        }
                        PluginError::InvalidResponse(e) => {
                            f.debug_tuple("PluginError::InvalidResponse")
                                .field(e)
                                .finish()
                        }
                        PluginError::ProviderUnavailable => {
                            f.debug_tuple("PluginError::ProviderUnavailable").finish()
                        }
                        PluginError::PluginUnavailable => {
                            f.debug_tuple("PluginError::PluginUnavailable").finish()
                        }
                        PluginError::Cancelled => {
                            f.debug_tuple("PluginError::Cancelled").finish()
                        }
                        PluginError::Internal(e) => {
                            f.debug_tuple("PluginError::Internal").field(e).finish()
                        }
                    }
                }
            }
            impl ::core::fmt::Display for PluginError {
                fn fmt(
                    &self,
                    f: &mut ::core::fmt::Formatter<'_>,
                ) -> ::core::fmt::Result {
                    write!(f, "{:?}", self)
                }
            }
            impl std::error::Error for PluginError {}
            /// Resource operation errors (ownership, direction, bounds, state).
            #[derive(Clone)]
            pub enum ResourceError {
                NotOwned,
                WrongDirection,
                Exhausted,
                OutOfBounds,
                Closed,
                Cancelled,
                Internal(_rt::String),
            }
            impl ::core::fmt::Debug for ResourceError {
                fn fmt(
                    &self,
                    f: &mut ::core::fmt::Formatter<'_>,
                ) -> ::core::fmt::Result {
                    match self {
                        ResourceError::NotOwned => {
                            f.debug_tuple("ResourceError::NotOwned").finish()
                        }
                        ResourceError::WrongDirection => {
                            f.debug_tuple("ResourceError::WrongDirection").finish()
                        }
                        ResourceError::Exhausted => {
                            f.debug_tuple("ResourceError::Exhausted").finish()
                        }
                        ResourceError::OutOfBounds => {
                            f.debug_tuple("ResourceError::OutOfBounds").finish()
                        }
                        ResourceError::Closed => {
                            f.debug_tuple("ResourceError::Closed").finish()
                        }
                        ResourceError::Cancelled => {
                            f.debug_tuple("ResourceError::Cancelled").finish()
                        }
                        ResourceError::Internal(e) => {
                            f.debug_tuple("ResourceError::Internal").field(e).finish()
                        }
                    }
                }
            }
            impl ::core::fmt::Display for ResourceError {
                fn fmt(
                    &self,
                    f: &mut ::core::fmt::Formatter<'_>,
                ) -> ::core::fmt::Result {
                    write!(f, "{:?}", self)
                }
            }
            impl std::error::Error for ResourceError {}
            /// Blob/stream direction. `input` = guest reads; `output` = guest writes.
            #[repr(u8)]
            #[derive(Clone, Copy, Eq, Ord, PartialEq, PartialOrd)]
            pub enum BlobDirection {
                Input,
                Output,
            }
            impl ::core::fmt::Debug for BlobDirection {
                fn fmt(
                    &self,
                    f: &mut ::core::fmt::Formatter<'_>,
                ) -> ::core::fmt::Result {
                    match self {
                        BlobDirection::Input => {
                            f.debug_tuple("BlobDirection::Input").finish()
                        }
                        BlobDirection::Output => {
                            f.debug_tuple("BlobDirection::Output").finish()
                        }
                    }
                }
            }
            impl BlobDirection {
                #[doc(hidden)]
                pub unsafe fn _lift(val: u8) -> BlobDirection {
                    if !cfg!(debug_assertions) {
                        return ::core::mem::transmute(val);
                    }
                    match val {
                        0 => BlobDirection::Input,
                        1 => BlobDirection::Output,
                        _ => panic!("invalid enum discriminant"),
                    }
                }
            }
            /// Immutable payload kind bound to a stream at creation. The host rejects mixed-kind
            /// non-terminal frames: a `network-binary` stream carries only `network-binary` frames
            /// (plus one terminal), and an `llm-delta` stream carries only `llm-delta` frames
            /// (plus one terminal). This keeps binary chunks and structured LLM deltas disjoint so
            /// the host/frontend never parses opaque bytes to classify a delta or terminal state.
            #[repr(u8)]
            #[derive(Clone, Copy, Eq, Ord, PartialEq, PartialOrd)]
            pub enum StreamKind {
                NetworkBinary,
                LlmDelta,
            }
            impl ::core::fmt::Debug for StreamKind {
                fn fmt(
                    &self,
                    f: &mut ::core::fmt::Formatter<'_>,
                ) -> ::core::fmt::Result {
                    match self {
                        StreamKind::NetworkBinary => {
                            f.debug_tuple("StreamKind::NetworkBinary").finish()
                        }
                        StreamKind::LlmDelta => {
                            f.debug_tuple("StreamKind::LlmDelta").finish()
                        }
                    }
                }
            }
            impl StreamKind {
                #[doc(hidden)]
                pub unsafe fn _lift(val: u8) -> StreamKind {
                    if !cfg!(debug_assertions) {
                        return ::core::mem::transmute(val);
                    }
                    match val {
                        0 => StreamKind::NetworkBinary,
                        1 => StreamKind::LlmDelta,
                        _ => panic!("invalid enum discriminant"),
                    }
                }
            }
            /// Media metadata for blob/stream payloads.
            #[derive(Clone)]
            pub struct MediaMetadata {
                pub content_type: Option<_rt::String>,
                pub byte_length: Option<u64>,
            }
            impl ::core::fmt::Debug for MediaMetadata {
                fn fmt(
                    &self,
                    f: &mut ::core::fmt::Formatter<'_>,
                ) -> ::core::fmt::Result {
                    f.debug_struct("MediaMetadata")
                        .field("content-type", &self.content_type)
                        .field("byte-length", &self.byte_length)
                        .finish()
                }
            }
            /// Closed LLM completion status. The host never infers this from opaque delta bytes.
            #[repr(u8)]
            #[derive(Clone, Copy, Eq, Ord, PartialEq, PartialOrd)]
            pub enum LlmCompletionStatus {
                Stop,
                Length,
                ToolCalls,
            }
            impl ::core::fmt::Debug for LlmCompletionStatus {
                fn fmt(
                    &self,
                    f: &mut ::core::fmt::Formatter<'_>,
                ) -> ::core::fmt::Result {
                    match self {
                        LlmCompletionStatus::Stop => {
                            f.debug_tuple("LlmCompletionStatus::Stop").finish()
                        }
                        LlmCompletionStatus::Length => {
                            f.debug_tuple("LlmCompletionStatus::Length").finish()
                        }
                        LlmCompletionStatus::ToolCalls => {
                            f.debug_tuple("LlmCompletionStatus::ToolCalls").finish()
                        }
                    }
                }
            }
            impl LlmCompletionStatus {
                #[doc(hidden)]
                pub unsafe fn _lift(val: u8) -> LlmCompletionStatus {
                    if !cfg!(debug_assertions) {
                        return ::core::mem::transmute(val);
                    }
                    match val {
                        0 => LlmCompletionStatus::Stop,
                        1 => LlmCompletionStatus::Length,
                        2 => LlmCompletionStatus::ToolCalls,
                        _ => panic!("invalid enum discriminant"),
                    }
                }
            }
            /// Structured tool-call delta. Arguments are copied JSON bytes, never an opaque stream.
            #[derive(Clone)]
            pub struct LlmToolCallDelta {
                pub id: _rt::String,
                pub name: _rt::String,
                pub arguments_json: JsonBytes,
            }
            impl ::core::fmt::Debug for LlmToolCallDelta {
                fn fmt(
                    &self,
                    f: &mut ::core::fmt::Formatter<'_>,
                ) -> ::core::fmt::Result {
                    f.debug_struct("LlmToolCallDelta")
                        .field("id", &self.id)
                        .field("name", &self.name)
                        .field("arguments-json", &self.arguments_json)
                        .finish()
                }
            }
            /// Closed structured LLM delta contract for v1 streaming chat.
            #[derive(Clone)]
            pub enum LlmDelta {
                Text(_rt::String),
                Reasoning(_rt::String),
                ToolCall(LlmToolCallDelta),
                Complete(LlmCompletionStatus),
            }
            impl ::core::fmt::Debug for LlmDelta {
                fn fmt(
                    &self,
                    f: &mut ::core::fmt::Formatter<'_>,
                ) -> ::core::fmt::Result {
                    match self {
                        LlmDelta::Text(e) => {
                            f.debug_tuple("LlmDelta::Text").field(e).finish()
                        }
                        LlmDelta::Reasoning(e) => {
                            f.debug_tuple("LlmDelta::Reasoning").field(e).finish()
                        }
                        LlmDelta::ToolCall(e) => {
                            f.debug_tuple("LlmDelta::ToolCall").field(e).finish()
                        }
                        LlmDelta::Complete(e) => {
                            f.debug_tuple("LlmDelta::Complete").field(e).finish()
                        }
                    }
                }
            }
            /// Terminal state of a stream, queryable via `host.stream-state` and terminal frames.
            #[derive(Clone)]
            pub enum StreamTerminalState {
                Finished,
                Failed(_rt::String),
                Cancelled,
            }
            impl ::core::fmt::Debug for StreamTerminalState {
                fn fmt(
                    &self,
                    f: &mut ::core::fmt::Formatter<'_>,
                ) -> ::core::fmt::Result {
                    match self {
                        StreamTerminalState::Finished => {
                            f.debug_tuple("StreamTerminalState::Finished").finish()
                        }
                        StreamTerminalState::Failed(e) => {
                            f.debug_tuple("StreamTerminalState::Failed")
                                .field(e)
                                .finish()
                        }
                        StreamTerminalState::Cancelled => {
                            f.debug_tuple("StreamTerminalState::Cancelled").finish()
                        }
                    }
                }
            }
            /// Ordered typed stream frame. Network binary chunks and LLM deltas remain distinct, so
            /// the host/frontend never parses opaque bytes to classify a delta or terminal state.
            #[derive(Clone)]
            pub enum StreamFrame {
                NetworkBinary(_rt::Vec<u8>),
                LlmDelta(LlmDelta),
                Terminal(StreamTerminalState),
            }
            impl ::core::fmt::Debug for StreamFrame {
                fn fmt(
                    &self,
                    f: &mut ::core::fmt::Formatter<'_>,
                ) -> ::core::fmt::Result {
                    match self {
                        StreamFrame::NetworkBinary(e) => {
                            f.debug_tuple("StreamFrame::NetworkBinary").field(e).finish()
                        }
                        StreamFrame::LlmDelta(e) => {
                            f.debug_tuple("StreamFrame::LlmDelta").field(e).finish()
                        }
                        StreamFrame::Terminal(e) => {
                            f.debug_tuple("StreamFrame::Terminal").field(e).finish()
                        }
                    }
                }
            }
            /// Opaque host-owned blob handle. Operations are host imports (see `host`). Handles are
            /// host table indices scoped to one principal/request; they cannot be persisted or reused.
            #[derive(Debug)]
            #[repr(transparent)]
            pub struct BlobHandle {
                handle: _rt::Resource<BlobHandle>,
            }
            impl BlobHandle {
                #[doc(hidden)]
                pub unsafe fn from_handle(handle: u32) -> Self {
                    Self {
                        handle: unsafe { _rt::Resource::from_handle(handle) },
                    }
                }
                #[doc(hidden)]
                pub fn take_handle(&self) -> u32 {
                    _rt::Resource::take_handle(&self.handle)
                }
                #[doc(hidden)]
                pub fn handle(&self) -> u32 {
                    _rt::Resource::handle(&self.handle)
                }
            }
            unsafe impl _rt::WasmResource for BlobHandle {
                #[inline]
                unsafe fn drop(_handle: u32) {
                    #[cfg(not(target_arch = "wasm32"))]
                    unreachable!();
                    #[cfg(target_arch = "wasm32")]
                    {
                        #[link(
                            wasm_import_module = "langnext:runtime-plugin/common@1.0.0"
                        )]
                        unsafe extern "C" {
                            #[link_name = "[resource-drop]blob-handle"]
                            fn drop(_: u32);
                        }
                        unsafe { drop(_handle) };
                    }
                }
            }
            /// Opaque host-owned stream handle. Operations are host imports (see `host`).
            /// Producer and consumer endpoints are separate resources so the host can read while a
            /// guest writes. Writers are transferred into a capability call; readers stay with the host.
            #[derive(Debug)]
            #[repr(transparent)]
            pub struct StreamWriter {
                handle: _rt::Resource<StreamWriter>,
            }
            impl StreamWriter {
                #[doc(hidden)]
                pub unsafe fn from_handle(handle: u32) -> Self {
                    Self {
                        handle: unsafe { _rt::Resource::from_handle(handle) },
                    }
                }
                #[doc(hidden)]
                pub fn take_handle(&self) -> u32 {
                    _rt::Resource::take_handle(&self.handle)
                }
                #[doc(hidden)]
                pub fn handle(&self) -> u32 {
                    _rt::Resource::handle(&self.handle)
                }
            }
            unsafe impl _rt::WasmResource for StreamWriter {
                #[inline]
                unsafe fn drop(_handle: u32) {
                    #[cfg(not(target_arch = "wasm32"))]
                    unreachable!();
                    #[cfg(target_arch = "wasm32")]
                    {
                        #[link(
                            wasm_import_module = "langnext:runtime-plugin/common@1.0.0"
                        )]
                        unsafe extern "C" {
                            #[link_name = "[resource-drop]stream-writer"]
                            fn drop(_: u32);
                        }
                        unsafe { drop(_handle) };
                    }
                }
            }
            #[derive(Debug)]
            #[repr(transparent)]
            pub struct StreamReader {
                handle: _rt::Resource<StreamReader>,
            }
            impl StreamReader {
                #[doc(hidden)]
                pub unsafe fn from_handle(handle: u32) -> Self {
                    Self {
                        handle: unsafe { _rt::Resource::from_handle(handle) },
                    }
                }
                #[doc(hidden)]
                pub fn take_handle(&self) -> u32 {
                    _rt::Resource::take_handle(&self.handle)
                }
                #[doc(hidden)]
                pub fn handle(&self) -> u32 {
                    _rt::Resource::handle(&self.handle)
                }
            }
            unsafe impl _rt::WasmResource for StreamReader {
                #[inline]
                unsafe fn drop(_handle: u32) {
                    #[cfg(not(target_arch = "wasm32"))]
                    unreachable!();
                    #[cfg(target_arch = "wasm32")]
                    {
                        #[link(
                            wasm_import_module = "langnext:runtime-plugin/common@1.0.0"
                        )]
                        unsafe extern "C" {
                            #[link_name = "[resource-drop]stream-reader"]
                            fn drop(_: u32);
                        }
                        unsafe { drop(_handle) };
                    }
                }
            }
        }
    }
}
#[rustfmt::skip]
#[allow(dead_code, clippy::all)]
pub mod exports {
    pub mod langnext {
        pub mod runtime_plugin {
            /// ABOUTME: Capability worlds and the pure copied-JSON migration world for the langnext
            /// ABOUTME: runtime-plugin v1 WIT package. Each world imports only `common` and `host`.
            /// Pure copied-JSON config/preference migration exports. No network, blobs, or streams.
            #[allow(dead_code, async_fn_in_trait, unused_imports, clippy::all)]
            pub mod migration {
                #[used]
                #[doc(hidden)]
                static __FORCE_SECTION_REF: fn() = super::super::super::super::__link_custom_section_describing_imports;
                use super::super::super::super::_rt;
                pub type JsonBytes = super::super::super::super::langnext::runtime_plugin::common::JsonBytes;
                pub type PluginError = super::super::super::super::langnext::runtime_plugin::common::PluginError;
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn _export_migrate_config_cabi<T: Guest>(
                    arg0: i32,
                    arg1: i32,
                    arg2: *mut u8,
                    arg3: usize,
                ) -> *mut u8 {
                    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
                    let len0 = arg3;
                    let result1 = T::migrate_config(
                        arg0 as u32,
                        arg1 as u32,
                        _rt::Vec::from_raw_parts(arg2.cast(), len0, len0),
                    );
                    let ptr2 = (&raw mut _RET_AREA.0).cast::<u8>();
                    match result1 {
                        Ok(e) => {
                            *ptr2.add(0).cast::<u8>() = (0i32) as u8;
                            let vec3 = (e).into_boxed_slice();
                            let ptr3 = vec3.as_ptr().cast::<u8>();
                            let len3 = vec3.len();
                            ::core::mem::forget(vec3);
                            *ptr2
                                .add(2 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>() = len3;
                            *ptr2
                                .add(::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>() = ptr3.cast_mut();
                        }
                        Err(e) => {
                            *ptr2.add(0).cast::<u8>() = (1i32) as u8;
                            use super::super::super::super::langnext::runtime_plugin::common::PluginError as V11;
                            match e {
                                V11::InvalidRequest(e) => {
                                    *ptr2
                                        .add(::core::mem::size_of::<*const u8>())
                                        .cast::<u8>() = (0i32) as u8;
                                    let vec4 = (e.into_bytes()).into_boxed_slice();
                                    let ptr4 = vec4.as_ptr().cast::<u8>();
                                    let len4 = vec4.len();
                                    ::core::mem::forget(vec4);
                                    *ptr2
                                        .add(3 * ::core::mem::size_of::<*const u8>())
                                        .cast::<usize>() = len4;
                                    *ptr2
                                        .add(2 * ::core::mem::size_of::<*const u8>())
                                        .cast::<*mut u8>() = ptr4.cast_mut();
                                }
                                V11::InvalidConfiguration => {
                                    *ptr2
                                        .add(::core::mem::size_of::<*const u8>())
                                        .cast::<u8>() = (1i32) as u8;
                                }
                                V11::InvalidInput(e) => {
                                    *ptr2
                                        .add(::core::mem::size_of::<*const u8>())
                                        .cast::<u8>() = (2i32) as u8;
                                    let vec5 = (e.into_bytes()).into_boxed_slice();
                                    let ptr5 = vec5.as_ptr().cast::<u8>();
                                    let len5 = vec5.len();
                                    ::core::mem::forget(vec5);
                                    *ptr2
                                        .add(3 * ::core::mem::size_of::<*const u8>())
                                        .cast::<usize>() = len5;
                                    *ptr2
                                        .add(2 * ::core::mem::size_of::<*const u8>())
                                        .cast::<*mut u8>() = ptr5.cast_mut();
                                }
                                V11::Auth => {
                                    *ptr2
                                        .add(::core::mem::size_of::<*const u8>())
                                        .cast::<u8>() = (3i32) as u8;
                                }
                                V11::PermissionDenied => {
                                    *ptr2
                                        .add(::core::mem::size_of::<*const u8>())
                                        .cast::<u8>() = (4i32) as u8;
                                }
                                V11::QuotaExceeded => {
                                    *ptr2
                                        .add(::core::mem::size_of::<*const u8>())
                                        .cast::<u8>() = (5i32) as u8;
                                }
                                V11::RateLimited => {
                                    *ptr2
                                        .add(::core::mem::size_of::<*const u8>())
                                        .cast::<u8>() = (6i32) as u8;
                                }
                                V11::UnsupportedInput(e) => {
                                    *ptr2
                                        .add(::core::mem::size_of::<*const u8>())
                                        .cast::<u8>() = (7i32) as u8;
                                    let vec6 = (e.into_bytes()).into_boxed_slice();
                                    let ptr6 = vec6.as_ptr().cast::<u8>();
                                    let len6 = vec6.len();
                                    ::core::mem::forget(vec6);
                                    *ptr2
                                        .add(3 * ::core::mem::size_of::<*const u8>())
                                        .cast::<usize>() = len6;
                                    *ptr2
                                        .add(2 * ::core::mem::size_of::<*const u8>())
                                        .cast::<*mut u8>() = ptr6.cast_mut();
                                }
                                V11::UnsupportedLanguage(e) => {
                                    *ptr2
                                        .add(::core::mem::size_of::<*const u8>())
                                        .cast::<u8>() = (8i32) as u8;
                                    let vec7 = (e.into_bytes()).into_boxed_slice();
                                    let ptr7 = vec7.as_ptr().cast::<u8>();
                                    let len7 = vec7.len();
                                    ::core::mem::forget(vec7);
                                    *ptr2
                                        .add(3 * ::core::mem::size_of::<*const u8>())
                                        .cast::<usize>() = len7;
                                    *ptr2
                                        .add(2 * ::core::mem::size_of::<*const u8>())
                                        .cast::<*mut u8>() = ptr7.cast_mut();
                                }
                                V11::Network(e) => {
                                    *ptr2
                                        .add(::core::mem::size_of::<*const u8>())
                                        .cast::<u8>() = (9i32) as u8;
                                    let vec8 = (e.into_bytes()).into_boxed_slice();
                                    let ptr8 = vec8.as_ptr().cast::<u8>();
                                    let len8 = vec8.len();
                                    ::core::mem::forget(vec8);
                                    *ptr2
                                        .add(3 * ::core::mem::size_of::<*const u8>())
                                        .cast::<usize>() = len8;
                                    *ptr2
                                        .add(2 * ::core::mem::size_of::<*const u8>())
                                        .cast::<*mut u8>() = ptr8.cast_mut();
                                }
                                V11::Timeout => {
                                    *ptr2
                                        .add(::core::mem::size_of::<*const u8>())
                                        .cast::<u8>() = (10i32) as u8;
                                }
                                V11::InvalidResponse(e) => {
                                    *ptr2
                                        .add(::core::mem::size_of::<*const u8>())
                                        .cast::<u8>() = (11i32) as u8;
                                    let vec9 = (e.into_bytes()).into_boxed_slice();
                                    let ptr9 = vec9.as_ptr().cast::<u8>();
                                    let len9 = vec9.len();
                                    ::core::mem::forget(vec9);
                                    *ptr2
                                        .add(3 * ::core::mem::size_of::<*const u8>())
                                        .cast::<usize>() = len9;
                                    *ptr2
                                        .add(2 * ::core::mem::size_of::<*const u8>())
                                        .cast::<*mut u8>() = ptr9.cast_mut();
                                }
                                V11::ProviderUnavailable => {
                                    *ptr2
                                        .add(::core::mem::size_of::<*const u8>())
                                        .cast::<u8>() = (12i32) as u8;
                                }
                                V11::PluginUnavailable => {
                                    *ptr2
                                        .add(::core::mem::size_of::<*const u8>())
                                        .cast::<u8>() = (13i32) as u8;
                                }
                                V11::Cancelled => {
                                    *ptr2
                                        .add(::core::mem::size_of::<*const u8>())
                                        .cast::<u8>() = (14i32) as u8;
                                }
                                V11::Internal(e) => {
                                    *ptr2
                                        .add(::core::mem::size_of::<*const u8>())
                                        .cast::<u8>() = (15i32) as u8;
                                    let vec10 = (e.into_bytes()).into_boxed_slice();
                                    let ptr10 = vec10.as_ptr().cast::<u8>();
                                    let len10 = vec10.len();
                                    ::core::mem::forget(vec10);
                                    *ptr2
                                        .add(3 * ::core::mem::size_of::<*const u8>())
                                        .cast::<usize>() = len10;
                                    *ptr2
                                        .add(2 * ::core::mem::size_of::<*const u8>())
                                        .cast::<*mut u8>() = ptr10.cast_mut();
                                }
                            }
                        }
                    };
                    ptr2
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn __post_return_migrate_config<T: Guest>(arg0: *mut u8) {
                    let l0 = i32::from(*arg0.add(0).cast::<u8>());
                    match l0 {
                        0 => {
                            let l1 = *arg0
                                .add(::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>();
                            let l2 = *arg0
                                .add(2 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>();
                            let base3 = l1;
                            let len3 = l2;
                            _rt::cabi_dealloc(base3, len3 * 1, 1);
                        }
                        _ => {
                            let l4 = i32::from(
                                *arg0.add(::core::mem::size_of::<*const u8>()).cast::<u8>(),
                            );
                            match l4 {
                                0 => {
                                    let l5 = *arg0
                                        .add(2 * ::core::mem::size_of::<*const u8>())
                                        .cast::<*mut u8>();
                                    let l6 = *arg0
                                        .add(3 * ::core::mem::size_of::<*const u8>())
                                        .cast::<usize>();
                                    _rt::cabi_dealloc(l5, l6, 1);
                                }
                                1 => {}
                                2 => {
                                    let l7 = *arg0
                                        .add(2 * ::core::mem::size_of::<*const u8>())
                                        .cast::<*mut u8>();
                                    let l8 = *arg0
                                        .add(3 * ::core::mem::size_of::<*const u8>())
                                        .cast::<usize>();
                                    _rt::cabi_dealloc(l7, l8, 1);
                                }
                                3 => {}
                                4 => {}
                                5 => {}
                                6 => {}
                                7 => {
                                    let l9 = *arg0
                                        .add(2 * ::core::mem::size_of::<*const u8>())
                                        .cast::<*mut u8>();
                                    let l10 = *arg0
                                        .add(3 * ::core::mem::size_of::<*const u8>())
                                        .cast::<usize>();
                                    _rt::cabi_dealloc(l9, l10, 1);
                                }
                                8 => {
                                    let l11 = *arg0
                                        .add(2 * ::core::mem::size_of::<*const u8>())
                                        .cast::<*mut u8>();
                                    let l12 = *arg0
                                        .add(3 * ::core::mem::size_of::<*const u8>())
                                        .cast::<usize>();
                                    _rt::cabi_dealloc(l11, l12, 1);
                                }
                                9 => {
                                    let l13 = *arg0
                                        .add(2 * ::core::mem::size_of::<*const u8>())
                                        .cast::<*mut u8>();
                                    let l14 = *arg0
                                        .add(3 * ::core::mem::size_of::<*const u8>())
                                        .cast::<usize>();
                                    _rt::cabi_dealloc(l13, l14, 1);
                                }
                                10 => {}
                                11 => {
                                    let l15 = *arg0
                                        .add(2 * ::core::mem::size_of::<*const u8>())
                                        .cast::<*mut u8>();
                                    let l16 = *arg0
                                        .add(3 * ::core::mem::size_of::<*const u8>())
                                        .cast::<usize>();
                                    _rt::cabi_dealloc(l15, l16, 1);
                                }
                                12 => {}
                                13 => {}
                                14 => {}
                                _ => {
                                    let l17 = *arg0
                                        .add(2 * ::core::mem::size_of::<*const u8>())
                                        .cast::<*mut u8>();
                                    let l18 = *arg0
                                        .add(3 * ::core::mem::size_of::<*const u8>())
                                        .cast::<usize>();
                                    _rt::cabi_dealloc(l17, l18, 1);
                                }
                            }
                        }
                    }
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn _export_migrate_preferences_cabi<T: Guest>(
                    arg0: *mut u8,
                    arg1: usize,
                    arg2: i32,
                    arg3: i32,
                    arg4: *mut u8,
                    arg5: usize,
                ) -> *mut u8 {
                    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
                    let len0 = arg1;
                    let bytes0 = _rt::Vec::from_raw_parts(arg0.cast(), len0, len0);
                    let len1 = arg5;
                    let result2 = T::migrate_preferences(
                        _rt::string_lift(bytes0),
                        arg2 as u32,
                        arg3 as u32,
                        _rt::Vec::from_raw_parts(arg4.cast(), len1, len1),
                    );
                    let ptr3 = (&raw mut _RET_AREA.0).cast::<u8>();
                    match result2 {
                        Ok(e) => {
                            *ptr3.add(0).cast::<u8>() = (0i32) as u8;
                            let vec4 = (e).into_boxed_slice();
                            let ptr4 = vec4.as_ptr().cast::<u8>();
                            let len4 = vec4.len();
                            ::core::mem::forget(vec4);
                            *ptr3
                                .add(2 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>() = len4;
                            *ptr3
                                .add(::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>() = ptr4.cast_mut();
                        }
                        Err(e) => {
                            *ptr3.add(0).cast::<u8>() = (1i32) as u8;
                            use super::super::super::super::langnext::runtime_plugin::common::PluginError as V12;
                            match e {
                                V12::InvalidRequest(e) => {
                                    *ptr3
                                        .add(::core::mem::size_of::<*const u8>())
                                        .cast::<u8>() = (0i32) as u8;
                                    let vec5 = (e.into_bytes()).into_boxed_slice();
                                    let ptr5 = vec5.as_ptr().cast::<u8>();
                                    let len5 = vec5.len();
                                    ::core::mem::forget(vec5);
                                    *ptr3
                                        .add(3 * ::core::mem::size_of::<*const u8>())
                                        .cast::<usize>() = len5;
                                    *ptr3
                                        .add(2 * ::core::mem::size_of::<*const u8>())
                                        .cast::<*mut u8>() = ptr5.cast_mut();
                                }
                                V12::InvalidConfiguration => {
                                    *ptr3
                                        .add(::core::mem::size_of::<*const u8>())
                                        .cast::<u8>() = (1i32) as u8;
                                }
                                V12::InvalidInput(e) => {
                                    *ptr3
                                        .add(::core::mem::size_of::<*const u8>())
                                        .cast::<u8>() = (2i32) as u8;
                                    let vec6 = (e.into_bytes()).into_boxed_slice();
                                    let ptr6 = vec6.as_ptr().cast::<u8>();
                                    let len6 = vec6.len();
                                    ::core::mem::forget(vec6);
                                    *ptr3
                                        .add(3 * ::core::mem::size_of::<*const u8>())
                                        .cast::<usize>() = len6;
                                    *ptr3
                                        .add(2 * ::core::mem::size_of::<*const u8>())
                                        .cast::<*mut u8>() = ptr6.cast_mut();
                                }
                                V12::Auth => {
                                    *ptr3
                                        .add(::core::mem::size_of::<*const u8>())
                                        .cast::<u8>() = (3i32) as u8;
                                }
                                V12::PermissionDenied => {
                                    *ptr3
                                        .add(::core::mem::size_of::<*const u8>())
                                        .cast::<u8>() = (4i32) as u8;
                                }
                                V12::QuotaExceeded => {
                                    *ptr3
                                        .add(::core::mem::size_of::<*const u8>())
                                        .cast::<u8>() = (5i32) as u8;
                                }
                                V12::RateLimited => {
                                    *ptr3
                                        .add(::core::mem::size_of::<*const u8>())
                                        .cast::<u8>() = (6i32) as u8;
                                }
                                V12::UnsupportedInput(e) => {
                                    *ptr3
                                        .add(::core::mem::size_of::<*const u8>())
                                        .cast::<u8>() = (7i32) as u8;
                                    let vec7 = (e.into_bytes()).into_boxed_slice();
                                    let ptr7 = vec7.as_ptr().cast::<u8>();
                                    let len7 = vec7.len();
                                    ::core::mem::forget(vec7);
                                    *ptr3
                                        .add(3 * ::core::mem::size_of::<*const u8>())
                                        .cast::<usize>() = len7;
                                    *ptr3
                                        .add(2 * ::core::mem::size_of::<*const u8>())
                                        .cast::<*mut u8>() = ptr7.cast_mut();
                                }
                                V12::UnsupportedLanguage(e) => {
                                    *ptr3
                                        .add(::core::mem::size_of::<*const u8>())
                                        .cast::<u8>() = (8i32) as u8;
                                    let vec8 = (e.into_bytes()).into_boxed_slice();
                                    let ptr8 = vec8.as_ptr().cast::<u8>();
                                    let len8 = vec8.len();
                                    ::core::mem::forget(vec8);
                                    *ptr3
                                        .add(3 * ::core::mem::size_of::<*const u8>())
                                        .cast::<usize>() = len8;
                                    *ptr3
                                        .add(2 * ::core::mem::size_of::<*const u8>())
                                        .cast::<*mut u8>() = ptr8.cast_mut();
                                }
                                V12::Network(e) => {
                                    *ptr3
                                        .add(::core::mem::size_of::<*const u8>())
                                        .cast::<u8>() = (9i32) as u8;
                                    let vec9 = (e.into_bytes()).into_boxed_slice();
                                    let ptr9 = vec9.as_ptr().cast::<u8>();
                                    let len9 = vec9.len();
                                    ::core::mem::forget(vec9);
                                    *ptr3
                                        .add(3 * ::core::mem::size_of::<*const u8>())
                                        .cast::<usize>() = len9;
                                    *ptr3
                                        .add(2 * ::core::mem::size_of::<*const u8>())
                                        .cast::<*mut u8>() = ptr9.cast_mut();
                                }
                                V12::Timeout => {
                                    *ptr3
                                        .add(::core::mem::size_of::<*const u8>())
                                        .cast::<u8>() = (10i32) as u8;
                                }
                                V12::InvalidResponse(e) => {
                                    *ptr3
                                        .add(::core::mem::size_of::<*const u8>())
                                        .cast::<u8>() = (11i32) as u8;
                                    let vec10 = (e.into_bytes()).into_boxed_slice();
                                    let ptr10 = vec10.as_ptr().cast::<u8>();
                                    let len10 = vec10.len();
                                    ::core::mem::forget(vec10);
                                    *ptr3
                                        .add(3 * ::core::mem::size_of::<*const u8>())
                                        .cast::<usize>() = len10;
                                    *ptr3
                                        .add(2 * ::core::mem::size_of::<*const u8>())
                                        .cast::<*mut u8>() = ptr10.cast_mut();
                                }
                                V12::ProviderUnavailable => {
                                    *ptr3
                                        .add(::core::mem::size_of::<*const u8>())
                                        .cast::<u8>() = (12i32) as u8;
                                }
                                V12::PluginUnavailable => {
                                    *ptr3
                                        .add(::core::mem::size_of::<*const u8>())
                                        .cast::<u8>() = (13i32) as u8;
                                }
                                V12::Cancelled => {
                                    *ptr3
                                        .add(::core::mem::size_of::<*const u8>())
                                        .cast::<u8>() = (14i32) as u8;
                                }
                                V12::Internal(e) => {
                                    *ptr3
                                        .add(::core::mem::size_of::<*const u8>())
                                        .cast::<u8>() = (15i32) as u8;
                                    let vec11 = (e.into_bytes()).into_boxed_slice();
                                    let ptr11 = vec11.as_ptr().cast::<u8>();
                                    let len11 = vec11.len();
                                    ::core::mem::forget(vec11);
                                    *ptr3
                                        .add(3 * ::core::mem::size_of::<*const u8>())
                                        .cast::<usize>() = len11;
                                    *ptr3
                                        .add(2 * ::core::mem::size_of::<*const u8>())
                                        .cast::<*mut u8>() = ptr11.cast_mut();
                                }
                            }
                        }
                    };
                    ptr3
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn __post_return_migrate_preferences<T: Guest>(
                    arg0: *mut u8,
                ) {
                    let l0 = i32::from(*arg0.add(0).cast::<u8>());
                    match l0 {
                        0 => {
                            let l1 = *arg0
                                .add(::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>();
                            let l2 = *arg0
                                .add(2 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>();
                            let base3 = l1;
                            let len3 = l2;
                            _rt::cabi_dealloc(base3, len3 * 1, 1);
                        }
                        _ => {
                            let l4 = i32::from(
                                *arg0.add(::core::mem::size_of::<*const u8>()).cast::<u8>(),
                            );
                            match l4 {
                                0 => {
                                    let l5 = *arg0
                                        .add(2 * ::core::mem::size_of::<*const u8>())
                                        .cast::<*mut u8>();
                                    let l6 = *arg0
                                        .add(3 * ::core::mem::size_of::<*const u8>())
                                        .cast::<usize>();
                                    _rt::cabi_dealloc(l5, l6, 1);
                                }
                                1 => {}
                                2 => {
                                    let l7 = *arg0
                                        .add(2 * ::core::mem::size_of::<*const u8>())
                                        .cast::<*mut u8>();
                                    let l8 = *arg0
                                        .add(3 * ::core::mem::size_of::<*const u8>())
                                        .cast::<usize>();
                                    _rt::cabi_dealloc(l7, l8, 1);
                                }
                                3 => {}
                                4 => {}
                                5 => {}
                                6 => {}
                                7 => {
                                    let l9 = *arg0
                                        .add(2 * ::core::mem::size_of::<*const u8>())
                                        .cast::<*mut u8>();
                                    let l10 = *arg0
                                        .add(3 * ::core::mem::size_of::<*const u8>())
                                        .cast::<usize>();
                                    _rt::cabi_dealloc(l9, l10, 1);
                                }
                                8 => {
                                    let l11 = *arg0
                                        .add(2 * ::core::mem::size_of::<*const u8>())
                                        .cast::<*mut u8>();
                                    let l12 = *arg0
                                        .add(3 * ::core::mem::size_of::<*const u8>())
                                        .cast::<usize>();
                                    _rt::cabi_dealloc(l11, l12, 1);
                                }
                                9 => {
                                    let l13 = *arg0
                                        .add(2 * ::core::mem::size_of::<*const u8>())
                                        .cast::<*mut u8>();
                                    let l14 = *arg0
                                        .add(3 * ::core::mem::size_of::<*const u8>())
                                        .cast::<usize>();
                                    _rt::cabi_dealloc(l13, l14, 1);
                                }
                                10 => {}
                                11 => {
                                    let l15 = *arg0
                                        .add(2 * ::core::mem::size_of::<*const u8>())
                                        .cast::<*mut u8>();
                                    let l16 = *arg0
                                        .add(3 * ::core::mem::size_of::<*const u8>())
                                        .cast::<usize>();
                                    _rt::cabi_dealloc(l15, l16, 1);
                                }
                                12 => {}
                                13 => {}
                                14 => {}
                                _ => {
                                    let l17 = *arg0
                                        .add(2 * ::core::mem::size_of::<*const u8>())
                                        .cast::<*mut u8>();
                                    let l18 = *arg0
                                        .add(3 * ::core::mem::size_of::<*const u8>())
                                        .cast::<usize>();
                                    _rt::cabi_dealloc(l17, l18, 1);
                                }
                            }
                        }
                    }
                }
                pub trait Guest {
                    /// Migrate copied config JSON between schema versions. Pure: no IO, no execution.
                    fn migrate_config(
                        from_version: u32,
                        to_version: u32,
                        config: JsonBytes,
                    ) -> Result<JsonBytes, PluginError>;
                    /// Migrate copied preference JSON for a capability between schema versions.
                    fn migrate_preferences(
                        capability: _rt::String,
                        from_version: u32,
                        to_version: u32,
                        preferences: JsonBytes,
                    ) -> Result<JsonBytes, PluginError>;
                }
                #[doc(hidden)]
                macro_rules! __export_langnext_runtime_plugin_migration_1_0_0_cabi {
                    ($ty:ident with_types_in $($path_to_types:tt)*) => {
                        const _ : () = { #[unsafe (export_name =
                        "langnext:runtime-plugin/migration@1.0.0#migrate-config")] unsafe
                        extern "C" fn export_migrate_config(arg0 : i32, arg1 : i32, arg2
                        : * mut u8, arg3 : usize,) -> * mut u8 { unsafe {
                        $($path_to_types)*:: _export_migrate_config_cabi::<$ty > (arg0,
                        arg1, arg2, arg3) } } #[unsafe (export_name =
                        "cabi_post_langnext:runtime-plugin/migration@1.0.0#migrate-config")]
                        unsafe extern "C" fn _post_return_migrate_config(arg0 : * mut
                        u8,) { unsafe { $($path_to_types)*::
                        __post_return_migrate_config::<$ty > (arg0) } } #[unsafe
                        (export_name =
                        "langnext:runtime-plugin/migration@1.0.0#migrate-preferences")]
                        unsafe extern "C" fn export_migrate_preferences(arg0 : * mut u8,
                        arg1 : usize, arg2 : i32, arg3 : i32, arg4 : * mut u8, arg5 :
                        usize,) -> * mut u8 { unsafe { $($path_to_types)*::
                        _export_migrate_preferences_cabi::<$ty > (arg0, arg1, arg2, arg3,
                        arg4, arg5) } } #[unsafe (export_name =
                        "cabi_post_langnext:runtime-plugin/migration@1.0.0#migrate-preferences")]
                        unsafe extern "C" fn _post_return_migrate_preferences(arg0 : *
                        mut u8,) { unsafe { $($path_to_types)*::
                        __post_return_migrate_preferences::<$ty > (arg0) } } };
                    };
                }
                #[doc(hidden)]
                pub(crate) use __export_langnext_runtime_plugin_migration_1_0_0_cabi;
                #[cfg_attr(target_pointer_width = "64", repr(align(8)))]
                #[cfg_attr(target_pointer_width = "32", repr(align(4)))]
                struct _RetArea(
                    [::core::mem::MaybeUninit<
                        u8,
                    >; 4 * ::core::mem::size_of::<*const u8>()],
                );
                static mut _RET_AREA: _RetArea = _RetArea(
                    [::core::mem::MaybeUninit::uninit(); 4
                        * ::core::mem::size_of::<*const u8>()],
                );
            }
        }
    }
}
#[rustfmt::skip]
mod _rt {
    #![allow(dead_code, clippy::all)]
    pub use alloc_crate::string::String;
    pub use alloc_crate::vec::Vec;
    use core::fmt;
    use core::marker;
    use core::sync::atomic::{AtomicU32, Ordering::Relaxed};
    /// A type which represents a component model resource, either imported or
    /// exported into this component.
    ///
    /// This is a low-level wrapper which handles the lifetime of the resource
    /// (namely this has a destructor). The `T` provided defines the component model
    /// intrinsics that this wrapper uses.
    ///
    /// One of the chief purposes of this type is to provide `Deref` implementations
    /// to access the underlying data when it is owned.
    ///
    /// This type is primarily used in generated code for exported and imported
    /// resources.
    #[repr(transparent)]
    pub struct Resource<T: WasmResource> {
        handle: AtomicU32,
        _marker: marker::PhantomData<T>,
    }
    /// A trait which all wasm resources implement, namely providing the ability to
    /// drop a resource.
    ///
    /// This generally is implemented by generated code, not user-facing code.
    #[allow(clippy::missing_safety_doc)]
    pub unsafe trait WasmResource {
        /// Invokes the `[resource-drop]...` intrinsic.
        unsafe fn drop(handle: u32);
    }
    impl<T: WasmResource> Resource<T> {
        #[doc(hidden)]
        pub unsafe fn from_handle(handle: u32) -> Self {
            debug_assert!(handle != u32::MAX);
            Self {
                handle: AtomicU32::new(handle),
                _marker: marker::PhantomData,
            }
        }
        /// Takes ownership of the handle owned by `resource`.
        ///
        /// Note that this ideally would be `into_handle` taking `Resource<T>` by
        /// ownership. The code generator does not enable that in all situations,
        /// unfortunately, so this is provided instead.
        ///
        /// Also note that `take_handle` is in theory only ever called on values
        /// owned by a generated function. For example a generated function might
        /// take `Resource<T>` as an argument but then call `take_handle` on a
        /// reference to that argument. In that sense the dynamic nature of
        /// `take_handle` should only be exposed internally to generated code, not
        /// to user code.
        #[doc(hidden)]
        pub fn take_handle(resource: &Resource<T>) -> u32 {
            resource.handle.swap(u32::MAX, Relaxed)
        }
        #[doc(hidden)]
        pub fn handle(resource: &Resource<T>) -> u32 {
            resource.handle.load(Relaxed)
        }
    }
    impl<T: WasmResource> fmt::Debug for Resource<T> {
        fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
            f.debug_struct("Resource").field("handle", &self.handle).finish()
        }
    }
    impl<T: WasmResource> Drop for Resource<T> {
        fn drop(&mut self) {
            unsafe {
                match self.handle.load(Relaxed) {
                    u32::MAX => {}
                    other => T::drop(other),
                }
            }
        }
    }
    #[cfg(target_arch = "wasm32")]
    pub fn run_ctors_once() {
        wit_bindgen_rt::run_ctors_once();
    }
    pub unsafe fn cabi_dealloc(ptr: *mut u8, size: usize, align: usize) {
        if size == 0 {
            return;
        }
        let layout = alloc::Layout::from_size_align_unchecked(size, align);
        alloc::dealloc(ptr, layout);
    }
    pub unsafe fn string_lift(bytes: Vec<u8>) -> String {
        if cfg!(debug_assertions) {
            String::from_utf8(bytes).unwrap()
        } else {
            String::from_utf8_unchecked(bytes)
        }
    }
    extern crate alloc as alloc_crate;
    pub use alloc_crate::alloc;
}
/// Generates `#[unsafe(no_mangle)]` functions to export the specified type as
/// the root implementation of all generated traits.
///
/// For more information see the documentation of `wit_bindgen::generate!`.
///
/// ```rust
/// # macro_rules! export{ ($($t:tt)*) => (); }
/// # trait Guest {}
/// struct MyType;
///
/// impl Guest for MyType {
///     // ...
/// }
///
/// export!(MyType);
/// ```
#[allow(unused_macros)]
#[doc(hidden)]
macro_rules! __export_migration_world_impl {
    ($ty:ident) => {
        self::export!($ty with_types_in self);
    };
    ($ty:ident with_types_in $($path_to_types_root:tt)*) => {
        $($path_to_types_root)*::
        exports::langnext::runtime_plugin::migration::__export_langnext_runtime_plugin_migration_1_0_0_cabi!($ty
        with_types_in $($path_to_types_root)*::
        exports::langnext::runtime_plugin::migration);
    };
}
#[doc(inline)]
pub(crate) use __export_migration_world_impl as export;
#[cfg(target_arch = "wasm32")]
#[unsafe(
    link_section = "component-type:wit-bindgen:0.41.0:langnext:runtime-plugin@1.0.0:migration-world:encoded world"
)]
#[doc(hidden)]
#[allow(clippy::octal_escapes)]
pub static __WIT_BINDGEN_COMPONENT_TYPE: [u8; 1455] = *b"\
\0asm\x0d\0\x01\0\0\x19\x16wit-component-encoding\x04\0\x07\xa9\x0a\x01A\x02\x01\
A\x06\x01B\x20\x01s\x04\0\x0arequest-id\x03\0\0\x01s\x04\0\x0blanguage-id\x03\0\x02\
\x01p}\x04\0\x0ajson-bytes\x03\0\x04\x01q\x10\x0finvalid-request\x01s\0\x15inval\
id-configuration\0\0\x0dinvalid-input\x01s\0\x04auth\0\0\x11permission-denied\0\0\
\x0equota-exceeded\0\0\x0crate-limited\0\0\x11unsupported-input\x01s\0\x14unsupp\
orted-language\x01s\0\x07network\x01s\0\x07timeout\0\0\x10invalid-response\x01s\0\
\x14provider-unavailable\0\0\x12plugin-unavailable\0\0\x09cancelled\0\0\x08inter\
nal\x01s\0\x04\0\x0cplugin-error\x03\0\x06\x01q\x07\x09not-owned\0\0\x0fwrong-di\
rection\0\0\x09exhausted\0\0\x0dout-of-bounds\0\0\x06closed\0\0\x09cancelled\0\0\
\x08internal\x01s\0\x04\0\x0eresource-error\x03\0\x08\x01m\x02\x05input\x06outpu\
t\x04\0\x0eblob-direction\x03\0\x0a\x01m\x02\x0enetwork-binary\x09llm-delta\x04\0\
\x0bstream-kind\x03\0\x0c\x01ks\x01kw\x01r\x02\x0ccontent-type\x0e\x0bbyte-lengt\
h\x0f\x04\0\x0emedia-metadata\x03\0\x10\x01m\x03\x04stop\x06length\x0atool-calls\
\x04\0\x15llm-completion-status\x03\0\x12\x01r\x03\x02ids\x04names\x0earguments-\
json\x05\x04\0\x13llm-tool-call-delta\x03\0\x14\x01q\x04\x04text\x01s\0\x09reaso\
ning\x01s\0\x09tool-call\x01\x15\0\x08complete\x01\x13\0\x04\0\x09llm-delta\x03\0\
\x16\x01q\x03\x08finished\0\0\x06failed\x01s\0\x09cancelled\0\0\x04\0\x15stream-\
terminal-state\x03\0\x18\x01p}\x01q\x03\x0enetwork-binary\x01\x1a\0\x09llm-delta\
\x01\x17\0\x08terminal\x01\x19\0\x04\0\x0cstream-frame\x03\0\x1b\x04\0\x0bblob-h\
andle\x03\x01\x04\0\x0dstream-writer\x03\x01\x04\0\x0dstream-reader\x03\x01\x03\0\
$langnext:runtime-plugin/common@1.0.0\x05\0\x02\x03\0\0\x0ajson-bytes\x02\x03\0\0\
\x0cplugin-error\x01B\x09\x02\x03\x02\x01\x01\x04\0\x0ajson-bytes\x03\0\0\x02\x03\
\x02\x01\x02\x04\0\x0cplugin-error\x03\0\x02\x01j\x01\x01\x01\x03\x01@\x03\x0cfr\
om-versiony\x0ato-versiony\x06config\x01\0\x04\x04\0\x0emigrate-config\x01\x05\x01\
@\x04\x0acapabilitys\x0cfrom-versiony\x0ato-versiony\x0bpreferences\x01\0\x04\x04\
\0\x13migrate-preferences\x01\x06\x04\0'langnext:runtime-plugin/migration@1.0.0\x05\
\x03\x04\0-langnext:runtime-plugin/migration-world@1.0.0\x04\0\x0b\x15\x01\0\x0f\
migration-world\x03\0\0\0G\x09producers\x01\x0cprocessed-by\x02\x0dwit-component\
\x070.227.1\x10wit-bindgen-rust\x060.41.0";
#[inline(never)]
#[doc(hidden)]
pub fn __link_custom_section_describing_imports() {
    wit_bindgen_rt::maybe_link_cabi_realloc();
}
