/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root"
import { Route as SettingsRouteImport } from "./routes/settings"
import { Route as ModelsRouteImport } from "./routes/models"
import { Route as AboutRouteImport } from "./routes/about"
import { Route as IndexRouteImport } from "./routes/index"
import { Route as ModelsIndexRouteImport } from "./routes/models/index"
import { Route as ModelsProviderIdRouteImport } from "./routes/models/$providerId"

const SettingsRoute = SettingsRouteImport.update({
  id: "/settings",
  path: "/settings",
  getParentRoute: () => rootRouteImport,
} as any)
const ModelsRoute = ModelsRouteImport.update({
  id: "/models",
  path: "/models",
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: "/about",
  path: "/about",
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any)
const ModelsIndexRoute = ModelsIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => ModelsRoute,
} as any)
const ModelsProviderIdRoute = ModelsProviderIdRouteImport.update({
  id: "/$providerId",
  path: "/$providerId",
  getParentRoute: () => ModelsRoute,
} as any)

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute
  "/about": typeof AboutRoute
  "/models": typeof ModelsRouteWithChildren
  "/settings": typeof SettingsRoute
  "/models/$providerId": typeof ModelsProviderIdRoute
  "/models/": typeof ModelsIndexRoute
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute
  "/about": typeof AboutRoute
  "/settings": typeof SettingsRoute
  "/models/$providerId": typeof ModelsProviderIdRoute
  "/models": typeof ModelsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  "/": typeof IndexRoute
  "/about": typeof AboutRoute
  "/models": typeof ModelsRouteWithChildren
  "/settings": typeof SettingsRoute
  "/models/$providerId": typeof ModelsProviderIdRoute
  "/models/": typeof ModelsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | "/"
    | "/about"
    | "/models"
    | "/settings"
    | "/models/$providerId"
    | "/models/"
  fileRoutesByTo: FileRoutesByTo
  to: "/" | "/about" | "/settings" | "/models/$providerId" | "/models"
  id:
    | "__root__"
    | "/"
    | "/about"
    | "/models"
    | "/settings"
    | "/models/$providerId"
    | "/models/"
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ModelsRoute: typeof ModelsRouteWithChildren
  SettingsRoute: typeof SettingsRoute
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/settings": {
      id: "/settings"
      path: "/settings"
      fullPath: "/settings"
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/models": {
      id: "/models"
      path: "/models"
      fullPath: "/models"
      preLoaderRoute: typeof ModelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/about": {
      id: "/about"
      path: "/about"
      fullPath: "/about"
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/": {
      id: "/"
      path: "/"
      fullPath: "/"
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/models/": {
      id: "/models/"
      path: "/"
      fullPath: "/models/"
      preLoaderRoute: typeof ModelsIndexRouteImport
      parentRoute: typeof ModelsRoute
    }
    "/models/$providerId": {
      id: "/models/$providerId"
      path: "/$providerId"
      fullPath: "/models/$providerId"
      preLoaderRoute: typeof ModelsProviderIdRouteImport
      parentRoute: typeof ModelsRoute
    }
  }
}

interface ModelsRouteChildren {
  ModelsProviderIdRoute: typeof ModelsProviderIdRoute
  ModelsIndexRoute: typeof ModelsIndexRoute
}

const ModelsRouteChildren: ModelsRouteChildren = {
  ModelsProviderIdRoute: ModelsProviderIdRoute,
  ModelsIndexRoute: ModelsIndexRoute,
}

const ModelsRouteWithChildren =
  ModelsRoute._addFileChildren(ModelsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ModelsRoute: ModelsRouteWithChildren,
  SettingsRoute: SettingsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
