/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root"
import { Route as TranslateRouteImport } from "./routes/translate"
import { Route as SettingsRouteImport } from "./routes/settings"
import { Route as QuickTranslateRouteImport } from "./routes/quick-translate"
import { Route as ModelsRouteImport } from "./routes/models"
import { Route as HistoryRouteImport } from "./routes/history"
import { Route as AboutRouteImport } from "./routes/about"
import { Route as IndexRouteImport } from "./routes/index"
import { Route as TranslateIndexRouteImport } from "./routes/translate/index"
import { Route as ModelsIndexRouteImport } from "./routes/models/index"
import { Route as TranslateProfilesRouteImport } from "./routes/translate/profiles"
import { Route as ModelsProviderIdRouteImport } from "./routes/models/$providerId"

const TranslateRoute = TranslateRouteImport.update({
  id: "/translate",
  path: "/translate",
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: "/settings",
  path: "/settings",
  getParentRoute: () => rootRouteImport,
} as any)
const QuickTranslateRoute = QuickTranslateRouteImport.update({
  id: "/quick-translate",
  path: "/quick-translate",
  getParentRoute: () => rootRouteImport,
} as any)
const ModelsRoute = ModelsRouteImport.update({
  id: "/models",
  path: "/models",
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: "/history",
  path: "/history",
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: "/about",
  path: "/about",
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any)
const TranslateIndexRoute = TranslateIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => TranslateRoute,
} as any)
const ModelsIndexRoute = ModelsIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => ModelsRoute,
} as any)
const TranslateProfilesRoute = TranslateProfilesRouteImport.update({
  id: "/profiles",
  path: "/profiles",
  getParentRoute: () => TranslateRoute,
} as any)
const ModelsProviderIdRoute = ModelsProviderIdRouteImport.update({
  id: "/$providerId",
  path: "/$providerId",
  getParentRoute: () => ModelsRoute,
} as any)

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute
  "/about": typeof AboutRoute
  "/history": typeof HistoryRoute
  "/models": typeof ModelsRouteWithChildren
  "/quick-translate": typeof QuickTranslateRoute
  "/settings": typeof SettingsRoute
  "/translate": typeof TranslateRouteWithChildren
  "/models/$providerId": typeof ModelsProviderIdRoute
  "/translate/profiles": typeof TranslateProfilesRoute
  "/models/": typeof ModelsIndexRoute
  "/translate/": typeof TranslateIndexRoute
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute
  "/about": typeof AboutRoute
  "/history": typeof HistoryRoute
  "/quick-translate": typeof QuickTranslateRoute
  "/settings": typeof SettingsRoute
  "/models/$providerId": typeof ModelsProviderIdRoute
  "/translate/profiles": typeof TranslateProfilesRoute
  "/models": typeof ModelsIndexRoute
  "/translate": typeof TranslateIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  "/": typeof IndexRoute
  "/about": typeof AboutRoute
  "/history": typeof HistoryRoute
  "/models": typeof ModelsRouteWithChildren
  "/quick-translate": typeof QuickTranslateRoute
  "/settings": typeof SettingsRoute
  "/translate": typeof TranslateRouteWithChildren
  "/models/$providerId": typeof ModelsProviderIdRoute
  "/translate/profiles": typeof TranslateProfilesRoute
  "/models/": typeof ModelsIndexRoute
  "/translate/": typeof TranslateIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | "/"
    | "/about"
    | "/history"
    | "/models"
    | "/quick-translate"
    | "/settings"
    | "/translate"
    | "/models/$providerId"
    | "/translate/profiles"
    | "/models/"
    | "/translate/"
  fileRoutesByTo: FileRoutesByTo
  to:
    | "/"
    | "/about"
    | "/history"
    | "/quick-translate"
    | "/settings"
    | "/models/$providerId"
    | "/translate/profiles"
    | "/models"
    | "/translate"
  id:
    | "__root__"
    | "/"
    | "/about"
    | "/history"
    | "/models"
    | "/quick-translate"
    | "/settings"
    | "/translate"
    | "/models/$providerId"
    | "/translate/profiles"
    | "/models/"
    | "/translate/"
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  HistoryRoute: typeof HistoryRoute
  ModelsRoute: typeof ModelsRouteWithChildren
  QuickTranslateRoute: typeof QuickTranslateRoute
  SettingsRoute: typeof SettingsRoute
  TranslateRoute: typeof TranslateRouteWithChildren
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/translate": {
      id: "/translate"
      path: "/translate"
      fullPath: "/translate"
      preLoaderRoute: typeof TranslateRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/settings": {
      id: "/settings"
      path: "/settings"
      fullPath: "/settings"
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/quick-translate": {
      id: "/quick-translate"
      path: "/quick-translate"
      fullPath: "/quick-translate"
      preLoaderRoute: typeof QuickTranslateRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/models": {
      id: "/models"
      path: "/models"
      fullPath: "/models"
      preLoaderRoute: typeof ModelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/history": {
      id: "/history"
      path: "/history"
      fullPath: "/history"
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/about": {
      id: "/about"
      path: "/about"
      fullPath: "/about"
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/": {
      id: "/"
      path: "/"
      fullPath: "/"
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/translate/": {
      id: "/translate/"
      path: "/"
      fullPath: "/translate/"
      preLoaderRoute: typeof TranslateIndexRouteImport
      parentRoute: typeof TranslateRoute
    }
    "/models/": {
      id: "/models/"
      path: "/"
      fullPath: "/models/"
      preLoaderRoute: typeof ModelsIndexRouteImport
      parentRoute: typeof ModelsRoute
    }
    "/translate/profiles": {
      id: "/translate/profiles"
      path: "/profiles"
      fullPath: "/translate/profiles"
      preLoaderRoute: typeof TranslateProfilesRouteImport
      parentRoute: typeof TranslateRoute
    }
    "/models/$providerId": {
      id: "/models/$providerId"
      path: "/$providerId"
      fullPath: "/models/$providerId"
      preLoaderRoute: typeof ModelsProviderIdRouteImport
      parentRoute: typeof ModelsRoute
    }
  }
}

interface ModelsRouteChildren {
  ModelsProviderIdRoute: typeof ModelsProviderIdRoute
  ModelsIndexRoute: typeof ModelsIndexRoute
}

const ModelsRouteChildren: ModelsRouteChildren = {
  ModelsProviderIdRoute: ModelsProviderIdRoute,
  ModelsIndexRoute: ModelsIndexRoute,
}

const ModelsRouteWithChildren =
  ModelsRoute._addFileChildren(ModelsRouteChildren)

interface TranslateRouteChildren {
  TranslateProfilesRoute: typeof TranslateProfilesRoute
  TranslateIndexRoute: typeof TranslateIndexRoute
}

const TranslateRouteChildren: TranslateRouteChildren = {
  TranslateProfilesRoute: TranslateProfilesRoute,
  TranslateIndexRoute: TranslateIndexRoute,
}

const TranslateRouteWithChildren = TranslateRoute._addFileChildren(
  TranslateRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  HistoryRoute: HistoryRoute,
  ModelsRoute: ModelsRouteWithChildren,
  QuickTranslateRoute: QuickTranslateRoute,
  SettingsRoute: SettingsRoute,
  TranslateRoute: TranslateRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
