/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root"
import { Route as TranslateRouteImport } from "./routes/translate"
import { Route as SpeechRouteImport } from "./routes/speech"
import { Route as SettingsRouteImport } from "./routes/settings"
import { Route as ScreenshotOverlayRouteImport } from "./routes/screenshot-overlay"
import { Route as QuickTranslateRouteImport } from "./routes/quick-translate"
import { Route as PluginsRouteImport } from "./routes/plugins"
import { Route as OcrRouteImport } from "./routes/ocr"
import { Route as ModelsRouteImport } from "./routes/models"
import { Route as HistoryRouteImport } from "./routes/history"
import { Route as IndexRouteImport } from "./routes/index"
import { Route as TranslateIndexRouteImport } from "./routes/translate/index"
import { Route as SpeechIndexRouteImport } from "./routes/speech/index"
import { Route as PluginsIndexRouteImport } from "./routes/plugins/index"
import { Route as OcrIndexRouteImport } from "./routes/ocr/index"
import { Route as ModelsIndexRouteImport } from "./routes/models/index"
import { Route as TranslateProfilesRouteImport } from "./routes/translate/profiles"
import { Route as SpeechSpeechServiceIdRouteImport } from "./routes/speech/$speechServiceId"
import { Route as PluginsIntegrationInstanceIdRouteImport } from "./routes/plugins/$integrationInstanceId"
import { Route as OcrOcrServiceIdRouteImport } from "./routes/ocr/$ocrServiceId"
import { Route as ModelsProviderIdRouteImport } from "./routes/models/$providerId"

const TranslateRoute = TranslateRouteImport.update({
  id: "/translate",
  path: "/translate",
  getParentRoute: () => rootRouteImport,
} as any)
const SpeechRoute = SpeechRouteImport.update({
  id: "/speech",
  path: "/speech",
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: "/settings",
  path: "/settings",
  getParentRoute: () => rootRouteImport,
} as any)
const ScreenshotOverlayRoute = ScreenshotOverlayRouteImport.update({
  id: "/screenshot-overlay",
  path: "/screenshot-overlay",
  getParentRoute: () => rootRouteImport,
} as any)
const QuickTranslateRoute = QuickTranslateRouteImport.update({
  id: "/quick-translate",
  path: "/quick-translate",
  getParentRoute: () => rootRouteImport,
} as any)
const PluginsRoute = PluginsRouteImport.update({
  id: "/plugins",
  path: "/plugins",
  getParentRoute: () => rootRouteImport,
} as any)
const OcrRoute = OcrRouteImport.update({
  id: "/ocr",
  path: "/ocr",
  getParentRoute: () => rootRouteImport,
} as any)
const ModelsRoute = ModelsRouteImport.update({
  id: "/models",
  path: "/models",
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: "/history",
  path: "/history",
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any)
const TranslateIndexRoute = TranslateIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => TranslateRoute,
} as any)
const SpeechIndexRoute = SpeechIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => SpeechRoute,
} as any)
const PluginsIndexRoute = PluginsIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => PluginsRoute,
} as any)
const OcrIndexRoute = OcrIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => OcrRoute,
} as any)
const ModelsIndexRoute = ModelsIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => ModelsRoute,
} as any)
const TranslateProfilesRoute = TranslateProfilesRouteImport.update({
  id: "/profiles",
  path: "/profiles",
  getParentRoute: () => TranslateRoute,
} as any)
const SpeechSpeechServiceIdRoute = SpeechSpeechServiceIdRouteImport.update({
  id: "/$speechServiceId",
  path: "/$speechServiceId",
  getParentRoute: () => SpeechRoute,
} as any)
const PluginsIntegrationInstanceIdRoute =
  PluginsIntegrationInstanceIdRouteImport.update({
    id: "/$integrationInstanceId",
    path: "/$integrationInstanceId",
    getParentRoute: () => PluginsRoute,
  } as any)
const OcrOcrServiceIdRoute = OcrOcrServiceIdRouteImport.update({
  id: "/$ocrServiceId",
  path: "/$ocrServiceId",
  getParentRoute: () => OcrRoute,
} as any)
const ModelsProviderIdRoute = ModelsProviderIdRouteImport.update({
  id: "/$providerId",
  path: "/$providerId",
  getParentRoute: () => ModelsRoute,
} as any)

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute
  "/history": typeof HistoryRoute
  "/models": typeof ModelsRouteWithChildren
  "/ocr": typeof OcrRouteWithChildren
  "/plugins": typeof PluginsRouteWithChildren
  "/quick-translate": typeof QuickTranslateRoute
  "/screenshot-overlay": typeof ScreenshotOverlayRoute
  "/settings": typeof SettingsRoute
  "/speech": typeof SpeechRouteWithChildren
  "/translate": typeof TranslateRouteWithChildren
  "/models/$providerId": typeof ModelsProviderIdRoute
  "/ocr/$ocrServiceId": typeof OcrOcrServiceIdRoute
  "/plugins/$integrationInstanceId": typeof PluginsIntegrationInstanceIdRoute
  "/speech/$speechServiceId": typeof SpeechSpeechServiceIdRoute
  "/translate/profiles": typeof TranslateProfilesRoute
  "/models/": typeof ModelsIndexRoute
  "/ocr/": typeof OcrIndexRoute
  "/plugins/": typeof PluginsIndexRoute
  "/speech/": typeof SpeechIndexRoute
  "/translate/": typeof TranslateIndexRoute
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute
  "/history": typeof HistoryRoute
  "/quick-translate": typeof QuickTranslateRoute
  "/screenshot-overlay": typeof ScreenshotOverlayRoute
  "/settings": typeof SettingsRoute
  "/models/$providerId": typeof ModelsProviderIdRoute
  "/ocr/$ocrServiceId": typeof OcrOcrServiceIdRoute
  "/plugins/$integrationInstanceId": typeof PluginsIntegrationInstanceIdRoute
  "/speech/$speechServiceId": typeof SpeechSpeechServiceIdRoute
  "/translate/profiles": typeof TranslateProfilesRoute
  "/models": typeof ModelsIndexRoute
  "/ocr": typeof OcrIndexRoute
  "/plugins": typeof PluginsIndexRoute
  "/speech": typeof SpeechIndexRoute
  "/translate": typeof TranslateIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  "/": typeof IndexRoute
  "/history": typeof HistoryRoute
  "/models": typeof ModelsRouteWithChildren
  "/ocr": typeof OcrRouteWithChildren
  "/plugins": typeof PluginsRouteWithChildren
  "/quick-translate": typeof QuickTranslateRoute
  "/screenshot-overlay": typeof ScreenshotOverlayRoute
  "/settings": typeof SettingsRoute
  "/speech": typeof SpeechRouteWithChildren
  "/translate": typeof TranslateRouteWithChildren
  "/models/$providerId": typeof ModelsProviderIdRoute
  "/ocr/$ocrServiceId": typeof OcrOcrServiceIdRoute
  "/plugins/$integrationInstanceId": typeof PluginsIntegrationInstanceIdRoute
  "/speech/$speechServiceId": typeof SpeechSpeechServiceIdRoute
  "/translate/profiles": typeof TranslateProfilesRoute
  "/models/": typeof ModelsIndexRoute
  "/ocr/": typeof OcrIndexRoute
  "/plugins/": typeof PluginsIndexRoute
  "/speech/": typeof SpeechIndexRoute
  "/translate/": typeof TranslateIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | "/"
    | "/history"
    | "/models"
    | "/ocr"
    | "/plugins"
    | "/quick-translate"
    | "/screenshot-overlay"
    | "/settings"
    | "/speech"
    | "/translate"
    | "/models/$providerId"
    | "/ocr/$ocrServiceId"
    | "/plugins/$integrationInstanceId"
    | "/speech/$speechServiceId"
    | "/translate/profiles"
    | "/models/"
    | "/ocr/"
    | "/plugins/"
    | "/speech/"
    | "/translate/"
  fileRoutesByTo: FileRoutesByTo
  to:
    | "/"
    | "/history"
    | "/quick-translate"
    | "/screenshot-overlay"
    | "/settings"
    | "/models/$providerId"
    | "/ocr/$ocrServiceId"
    | "/plugins/$integrationInstanceId"
    | "/speech/$speechServiceId"
    | "/translate/profiles"
    | "/models"
    | "/ocr"
    | "/plugins"
    | "/speech"
    | "/translate"
  id:
    | "__root__"
    | "/"
    | "/history"
    | "/models"
    | "/ocr"
    | "/plugins"
    | "/quick-translate"
    | "/screenshot-overlay"
    | "/settings"
    | "/speech"
    | "/translate"
    | "/models/$providerId"
    | "/ocr/$ocrServiceId"
    | "/plugins/$integrationInstanceId"
    | "/speech/$speechServiceId"
    | "/translate/profiles"
    | "/models/"
    | "/ocr/"
    | "/plugins/"
    | "/speech/"
    | "/translate/"
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HistoryRoute: typeof HistoryRoute
  ModelsRoute: typeof ModelsRouteWithChildren
  OcrRoute: typeof OcrRouteWithChildren
  PluginsRoute: typeof PluginsRouteWithChildren
  QuickTranslateRoute: typeof QuickTranslateRoute
  ScreenshotOverlayRoute: typeof ScreenshotOverlayRoute
  SettingsRoute: typeof SettingsRoute
  SpeechRoute: typeof SpeechRouteWithChildren
  TranslateRoute: typeof TranslateRouteWithChildren
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/translate": {
      id: "/translate"
      path: "/translate"
      fullPath: "/translate"
      preLoaderRoute: typeof TranslateRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/speech": {
      id: "/speech"
      path: "/speech"
      fullPath: "/speech"
      preLoaderRoute: typeof SpeechRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/settings": {
      id: "/settings"
      path: "/settings"
      fullPath: "/settings"
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/screenshot-overlay": {
      id: "/screenshot-overlay"
      path: "/screenshot-overlay"
      fullPath: "/screenshot-overlay"
      preLoaderRoute: typeof ScreenshotOverlayRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/quick-translate": {
      id: "/quick-translate"
      path: "/quick-translate"
      fullPath: "/quick-translate"
      preLoaderRoute: typeof QuickTranslateRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/plugins": {
      id: "/plugins"
      path: "/plugins"
      fullPath: "/plugins"
      preLoaderRoute: typeof PluginsRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/ocr": {
      id: "/ocr"
      path: "/ocr"
      fullPath: "/ocr"
      preLoaderRoute: typeof OcrRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/models": {
      id: "/models"
      path: "/models"
      fullPath: "/models"
      preLoaderRoute: typeof ModelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/history": {
      id: "/history"
      path: "/history"
      fullPath: "/history"
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/": {
      id: "/"
      path: "/"
      fullPath: "/"
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/translate/": {
      id: "/translate/"
      path: "/"
      fullPath: "/translate/"
      preLoaderRoute: typeof TranslateIndexRouteImport
      parentRoute: typeof TranslateRoute
    }
    "/speech/": {
      id: "/speech/"
      path: "/"
      fullPath: "/speech/"
      preLoaderRoute: typeof SpeechIndexRouteImport
      parentRoute: typeof SpeechRoute
    }
    "/plugins/": {
      id: "/plugins/"
      path: "/"
      fullPath: "/plugins/"
      preLoaderRoute: typeof PluginsIndexRouteImport
      parentRoute: typeof PluginsRoute
    }
    "/ocr/": {
      id: "/ocr/"
      path: "/"
      fullPath: "/ocr/"
      preLoaderRoute: typeof OcrIndexRouteImport
      parentRoute: typeof OcrRoute
    }
    "/models/": {
      id: "/models/"
      path: "/"
      fullPath: "/models/"
      preLoaderRoute: typeof ModelsIndexRouteImport
      parentRoute: typeof ModelsRoute
    }
    "/translate/profiles": {
      id: "/translate/profiles"
      path: "/profiles"
      fullPath: "/translate/profiles"
      preLoaderRoute: typeof TranslateProfilesRouteImport
      parentRoute: typeof TranslateRoute
    }
    "/speech/$speechServiceId": {
      id: "/speech/$speechServiceId"
      path: "/$speechServiceId"
      fullPath: "/speech/$speechServiceId"
      preLoaderRoute: typeof SpeechSpeechServiceIdRouteImport
      parentRoute: typeof SpeechRoute
    }
    "/plugins/$integrationInstanceId": {
      id: "/plugins/$integrationInstanceId"
      path: "/$integrationInstanceId"
      fullPath: "/plugins/$integrationInstanceId"
      preLoaderRoute: typeof PluginsIntegrationInstanceIdRouteImport
      parentRoute: typeof PluginsRoute
    }
    "/ocr/$ocrServiceId": {
      id: "/ocr/$ocrServiceId"
      path: "/$ocrServiceId"
      fullPath: "/ocr/$ocrServiceId"
      preLoaderRoute: typeof OcrOcrServiceIdRouteImport
      parentRoute: typeof OcrRoute
    }
    "/models/$providerId": {
      id: "/models/$providerId"
      path: "/$providerId"
      fullPath: "/models/$providerId"
      preLoaderRoute: typeof ModelsProviderIdRouteImport
      parentRoute: typeof ModelsRoute
    }
  }
}

interface ModelsRouteChildren {
  ModelsProviderIdRoute: typeof ModelsProviderIdRoute
  ModelsIndexRoute: typeof ModelsIndexRoute
}

const ModelsRouteChildren: ModelsRouteChildren = {
  ModelsProviderIdRoute: ModelsProviderIdRoute,
  ModelsIndexRoute: ModelsIndexRoute,
}

const ModelsRouteWithChildren =
  ModelsRoute._addFileChildren(ModelsRouteChildren)

interface OcrRouteChildren {
  OcrOcrServiceIdRoute: typeof OcrOcrServiceIdRoute
  OcrIndexRoute: typeof OcrIndexRoute
}

const OcrRouteChildren: OcrRouteChildren = {
  OcrOcrServiceIdRoute: OcrOcrServiceIdRoute,
  OcrIndexRoute: OcrIndexRoute,
}

const OcrRouteWithChildren = OcrRoute._addFileChildren(OcrRouteChildren)

interface PluginsRouteChildren {
  PluginsIntegrationInstanceIdRoute: typeof PluginsIntegrationInstanceIdRoute
  PluginsIndexRoute: typeof PluginsIndexRoute
}

const PluginsRouteChildren: PluginsRouteChildren = {
  PluginsIntegrationInstanceIdRoute: PluginsIntegrationInstanceIdRoute,
  PluginsIndexRoute: PluginsIndexRoute,
}

const PluginsRouteWithChildren =
  PluginsRoute._addFileChildren(PluginsRouteChildren)

interface SpeechRouteChildren {
  SpeechSpeechServiceIdRoute: typeof SpeechSpeechServiceIdRoute
  SpeechIndexRoute: typeof SpeechIndexRoute
}

const SpeechRouteChildren: SpeechRouteChildren = {
  SpeechSpeechServiceIdRoute: SpeechSpeechServiceIdRoute,
  SpeechIndexRoute: SpeechIndexRoute,
}

const SpeechRouteWithChildren =
  SpeechRoute._addFileChildren(SpeechRouteChildren)

interface TranslateRouteChildren {
  TranslateProfilesRoute: typeof TranslateProfilesRoute
  TranslateIndexRoute: typeof TranslateIndexRoute
}

const TranslateRouteChildren: TranslateRouteChildren = {
  TranslateProfilesRoute: TranslateProfilesRoute,
  TranslateIndexRoute: TranslateIndexRoute,
}

const TranslateRouteWithChildren = TranslateRoute._addFileChildren(
  TranslateRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HistoryRoute: HistoryRoute,
  ModelsRoute: ModelsRouteWithChildren,
  OcrRoute: OcrRouteWithChildren,
  PluginsRoute: PluginsRouteWithChildren,
  QuickTranslateRoute: QuickTranslateRoute,
  ScreenshotOverlayRoute: ScreenshotOverlayRoute,
  SettingsRoute: SettingsRoute,
  SpeechRoute: SpeechRouteWithChildren,
  TranslateRoute: TranslateRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
