[package]
name = "langnext-google-cloud-tts"
version = "1.2.0"
edition = "2021"
publish = false
license = "Apache-2.0"

[lib]
crate-type = ["cdylib"]

[features]
std = []

[dependencies]
wit-bindgen = { version = "=0.41.0", default-features = false, features = ["macros", "realloc"] }
base64 = { version = "0.22", default-features = false, features = ["alloc"] }
serde = { version = "1", default-features = false, features = ["alloc", "derive"] }
serde_json = { version = "1", default-features = false, features = ["alloc"] }
langnext-google-cloud-protocol = { path = "../protocol" }

[profile.release]
opt-level = "z"
lto = true
codegen-units = 1
panic = "abort"
strip = true

[package.metadata.component]
package = "langnext:google-cloud-tts"

[package.metadata.component.target]
path = "../../../src-tauri/wit/runtime-plugin"
world = "speech-synthesize-world"

[package.metadata.component.dependencies]
